import { CachePolicy, DefaultLogger, Logger } from '@sudoplatform/sudo-common'
import { EmailFolderService } from '../../entities/folder/emailFolderService'
import { FolderUseCaseOutput } from '../shared/folder'

/**
 * Input for `ListEmailFoldersForEmailAddressIdUseCase` use case.
 *
 * @interface ListEmailFoldersForEmailAddressIdUseCaseInput
 * @property {string} emailAddressId The identifier of the email address associated with the email folders.
 * @property {CachePolicy} cachePolicy Cache policy determines the strategy for accessing the folder records.
 * @property {number} limit Number of records to return. If omitted, the limit defaults to 10.
 * @property {string} nextToken A token generated by a previous call. This allows for pagination.
 */
interface ListEmailFoldersForEmailAddressIdUseCaseInput {
  emailAddressId: string
  cachePolicy?: CachePolicy
  limit?: number | undefined
  nextToken?: string | undefined
}

/**
 * Output for `ListEmailFoldersForEmailAddressIdUseCase` use case.
 *
 * @property {Array} folders The list of email folders retrieved in this use case.
 * @property {string} nextToken A token generated by a previous call. This allows for pagination.
 */
interface ListEmailFoldersForEmailAddressIdUseCaseOutput {
  folders: Array<FolderUseCaseOutput>
  nextToken?: string
}

/**
 * Application business logic for listing email folders.
 */
export class ListEmailFoldersForEmailAddressIdUseCase {
  private readonly log: Logger
  constructor(private readonly emailFolderService: EmailFolderService) {
    this.log = new DefaultLogger(this.constructor.name)
  }

  async execute({
    emailAddressId,
    cachePolicy,
    limit,
    nextToken,
  }: ListEmailFoldersForEmailAddressIdUseCaseInput): Promise<ListEmailFoldersForEmailAddressIdUseCaseOutput> {
    this.log.debug(this.constructor.name, {
      emailAddressId,
      cachePolicy,
      limit,
      nextToken,
    })
    return await this.emailFolderService.listEmailFoldersForEmailAddressId({
      emailAddressId,
      cachePolicy,
      limit,
      nextToken,
    })
  }
}
