import { CachePolicy } from '@sudoplatform/sudo-common'
import { EmailFolderFilter } from '../../../..'
import { EmailFolderEntity } from './emailFolderEntity'

/**
 * Input for `EmailFolderService.listEmailFoldersForEmailAddressId` method.
 *
 * @interface ListEmailFoldersForEmailAddressIdInput
 * @property {string} emailAddressId The identifier of the email address associated with the email folders.
 * @property {CachePolicy} cachePolicy Cache policy determines the strategy for accessing the folder records.
 * @property {EmailFolderFilterEntity} filter Only records that match this filter will be returned.
 * @property {number} limit Number of records to return. If omitted, the limit defaults to 10.
 * @property {string} nextToken A token generated by a previous call to listEmailFoldersForEmailAddressId.
 */
export interface ListEmailFoldersForEmailAddressIdInput {
  emailAddressId: string
  cachePolicy?: CachePolicy
  filter?: EmailFolderFilter
  limit?: number
  nextToken?: string
}

/**
 * Output for `EmailFolderService.listEmailFoldersForEmailAddressIdOutput` method.
 *
 * @interface ListEmailFoldersForEmailAddressIdOutput
 * @property {EmailFolderEntity[]} folders The list of email folders retrieved in this query.
 * @property {string} nextToken A token generated by a previous call. This allows for pagination.
 */
export interface ListEmailFoldersForEmailAddressIdOutput {
  folders: EmailFolderEntity[]
  nextToken?: string
}

/**
 * Core entity representation of an email folder service used in business logic. Used to perform operations for email folders.
 *
 * @interface EmailFolderService
 */
export interface EmailFolderService {
  /**
   * List the email folders from the service associated with the emailAddressId.
   *
   * @param {ListEmailFoldersForEmailAddressIdInput} input Parameters used to get a list of email folders for an email address.
   * @returns {ListEmailFoldersForEmailAddressIdOutput} The list of any email folders. Can be empty if no folders found.
   */
  listEmailFoldersForEmailAddressId(
    input: ListEmailFoldersForEmailAddressIdInput,
  ): Promise<ListEmailFoldersForEmailAddressIdOutput>
}
