/*
 * Copyright © 2024 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { CachePolicy } from '@sudoplatform/sudo-common'
import { EmailFolderEntity } from './emailFolderEntity'

/**
 * Input for `EmailFolderService.listEmailFoldersForEmailAddressId` method.
 *
 * @interface ListEmailFoldersForEmailAddressIdInput
 * @property {string} emailAddressId The identifier of the email address associated with the email folders.
 * @property {CachePolicy} cachePolicy Cache policy determines the strategy for accessing the folder records.
 * @property {number} limit Number of records to return. If omitted, the limit defaults to 10.
 * @property {string} nextToken A token generated by a previous call to listEmailFoldersForEmailAddressId.
 */
export interface ListEmailFoldersForEmailAddressIdInput {
  emailAddressId: string
  cachePolicy?: CachePolicy
  limit?: number
  nextToken?: string
}

/**
 * Output for `EmailFolderService.listEmailFoldersForEmailAddressIdOutput` method.
 *
 * @interface ListEmailFoldersForEmailAddressIdOutput
 * @property {EmailFolderEntity[]} folders The list of email folders retrieved in this query.
 * @property {string} nextToken A token generated by a previous call. This allows for pagination.
 */
export interface ListEmailFoldersForEmailAddressIdOutput {
  folders: EmailFolderEntity[]
  nextToken?: string
}

/**
 * Input for `EmailFolderService.createCustomEmailFolderForEmailAddressId` method.
 *
 * @interface CreateCustomEmailFolderForEmailAddressIdInput
 * @property {string} emailAddressId The identifier of the email address associated with the custom email folder.
 * @property {string} customFolderName The name of the custom email folder to be created.
 */
export interface CreateCustomEmailFolderForEmailAddressIdInput {
  emailAddressId: string
  customFolderName: string
}

/**
 * Core entity representation of an email folder service used in business logic. Used to perform operations for email folders.
 *
 * @interface EmailFolderService
 */
export interface EmailFolderService {
  /**
   * List the email folders from the service associated with the emailAddressId.
   *
   * @param {ListEmailFoldersForEmailAddressIdInput} input Parameters used to get a list of email folders for an email address.
   * @returns {ListEmailFoldersForEmailAddressIdOutput} The list of any email folders. Can be empty if no folders found.
   */
  listEmailFoldersForEmailAddressId(
    input: ListEmailFoldersForEmailAddressIdInput,
  ): Promise<ListEmailFoldersForEmailAddressIdOutput>

  /**
   * Create a custom email folder for the email address associated with the emailAddressId.
   *
   * @param {CreateCustomEmailFolderForEmailAddressIdInput} input Parameters used to create a custom email folder for an email address.
   * @returns {EmailFolderEntity} The custom email folder.
   */
  createCustomEmailFolderForEmailAddressId(
    input: CreateCustomEmailFolderForEmailAddressIdInput,
  ): Promise<EmailFolderEntity>
}
