/**
 * Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { DefaultLogger, Logger } from '@sudoplatform/sudo-common'
import { DraftEmailMessageEntity } from '../../entities/message/draftEmailMessageEntity'
import { EmailMessageService } from '../../entities/message/emailMessageService'

/**
 * Input for `ListDraftEmailMessagesForEmailAddressIdUseCase` use case.
 *
 * @interface ListDraftEmailMessagesForEmailAddressIdUseCaseInput
 * @property {string} emailAddressId Identifier of the email address associated with the draft email messages.
 * @property {number} limit Number of draft email messages to return. Defaults to 10.
 * @property {string} nextToken A token generated by a previous call for pagination.
 */
interface ListDraftEmailMessagesForEmailAddressIdUseCaseInput {
  emailAddressId: string
  limit?: number
  nextToken?: string
}

/**
 * Output for `ListDraftEmailMessagesForEmailAddressIdUseCase` use case.
 *
 * @interface ListDraftEmailMessagesForEmailAddressIdUseCaseOutput
 * @property {DraftEmailMessageEntity[]} draftMessages List of draft email messages.
 * @property {string} nextToken A token to pass to a subsequent call for pagination.
 */
interface ListDraftEmailMessagesForEmailAddressIdUseCaseOutput {
  draftMessages: DraftEmailMessageEntity[]
  nextToken?: string
}

/**
 * Application business logic for retrieving a list of draft email message metadata
 * and content for the specified email address.
 */
export class ListDraftEmailMessagesForEmailAddressIdUseCase {
  private readonly log: Logger
  constructor(private readonly emailMessageService: EmailMessageService) {
    this.log = new DefaultLogger(this.constructor.name)
  }

  async execute({
    emailAddressId,
    limit = 10,
    nextToken,
  }: ListDraftEmailMessagesForEmailAddressIdUseCaseInput): Promise<ListDraftEmailMessagesForEmailAddressIdUseCaseOutput> {
    this.log.debug(this.constructor.name, { emailAddressId, limit, nextToken })
    const metadata =
      await this.emailMessageService.listDraftsMetadataForEmailAddressId({
        emailAddressId,
        limit,
        nextToken,
      })
    const draftMessages = await Promise.all(
      metadata.items.map(async (m) => {
        const draft = await this.emailMessageService.getDraft({
          id: m.id,
          emailAddressId,
        })
        return draft
      }),
    )
    const result = draftMessages.filter(
      (draft) => draft !== undefined,
    ) as DraftEmailMessageEntity[]

    return { draftMessages: result, nextToken: metadata.nextToken }
  }
}
