/**
 * Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { DefaultLogger, Logger } from '@sudoplatform/sudo-common'
import { DraftEmailMessageMetadataEntity } from '../../entities/message/draftEmailMessageMetadataEntity'
import { EmailMessageService } from '../../entities/message/emailMessageService'

/**
 * Input for `ListDraftEmailMessageMetadataForEmailAddressIdUseCase` use case.
 *
 * @interface ListDraftEmailMessageMetadataForEmailAddressIdUseCaseInput
 * @property {string} emailAddressId Identifier of the email address associated with the draft email messages.
 * @property {number} limit Number of items to return. Will be defaulted to 10 if omitted.
 * @property {string} nextToken A token generated by a previous call for pagination.
 */
interface ListDraftEmailMessageMetadataForEmailAddressIdUseCaseInput {
  emailAddressId: string
  limit?: number
  nextToken?: string
}

/**
 * Output for `ListDraftEmailMessageMetadataForEmailAddressIdUseCase` use case.
 *
 * @interface ListDraftEmailMessageMetadataForEmailAddressIdUseCaseOutput
 * @property {DraftEmailMessageMetadataEntity[]} metadata List of draft email message metadata.
 * @property {string} nextToken Token to be used to fetch the next set of draft email messages, if any.
 */
interface ListDraftEmailMessageMetadataForEmailAddressIdUseCaseOutput {
  metadata: DraftEmailMessageMetadataEntity[]
  nextToken?: string
}

/**
 * Application business logic for retrieving a list of draft email message metadata
 * for the specified email address.
 */
export class ListDraftEmailMessageMetadataForEmailAddressIdUseCase {
  private readonly log: Logger
  constructor(private readonly emailMessageService: EmailMessageService) {
    this.log = new DefaultLogger(this.constructor.name)
  }

  async execute({
    emailAddressId,
    limit,
    nextToken,
  }: ListDraftEmailMessageMetadataForEmailAddressIdUseCaseInput): Promise<ListDraftEmailMessageMetadataForEmailAddressIdUseCaseOutput> {
    this.log.debug(this.constructor.name, { emailAddressId, limit, nextToken })
    const result =
      await this.emailMessageService.listDraftsMetadataForEmailAddressId({
        emailAddressId,
        limit,
        nextToken,
      })
    return {
      metadata: result.items,
      nextToken: result.nextToken,
    }
  }
}
