/**
 * Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { DefaultLogger, Logger } from '@sudoplatform/sudo-common'
import {
  EmailMaskService,
  EmailMaskFilterInput,
  ListEmailMasksOutput,
} from '../../entities/mask/emailMaskService'

/**
 * Input for `ListEmailMasksForOwnerUseCase` use case.
 *
 * @interface ListEmailMasksForOwnerUseCaseInput
 * @property {EmailMaskFilterInput} filter Used to filter results based on properties of the EmailMask
 * @property {number} limit Number of records to return. If omitted, the limit defaults to 10.
 * @property {string} nextToken A token generated by a previous call to `EmailMaskService.listEmailMasksForOwner`.
 */
interface ListEmailMasksForOwnerUseCaseInput {
  filter?: EmailMaskFilterInput
  limit?: number
  nextToken?: string
}

/**
 * Application business logic for listing email masks for the current owner.
 */
export class ListEmailMasksForOwnerUseCase {
  private readonly log: Logger

  constructor(private readonly emailMaskService: EmailMaskService) {
    this.log = new DefaultLogger(this.constructor.name)
  }

  async execute(
    input?: ListEmailMasksForOwnerUseCaseInput,
  ): Promise<ListEmailMasksOutput> {
    this.log.debug(this.constructor.name, {
      input,
    })

    return await this.emailMaskService.listEmailMasksForOwner(input)
  }
}
